### ISSUE TITLE
Error in Qwq.

### ISSUE THREAD

**Issue by GiovanniFyc** [openvinotoolkit/openvino.genai#1370] opened 2024-12-12 08:09 UTC
convert Qwq ,use the llm api,get error

**Comment by Wan-Intel** [comment] 2024-12-16 06:18
For your information, it's recommended to use models that are supported by OpenVINO™ GenAI. Please refer to [OpenVINO™ GenAI: Supported Models](https://github.com/openvinotoolkit/openvino.genai/blob/master/src/docs/SUPPORTED_MODELS.md#openvino-genai-supported-models) for the list of supported models. 

On the other hand, could you please share the model with us to further investigate the issue?

**Comment by avitial** [comment] 2024-12-26 21:13
Closing this due to insufficient info for reproduction. Feel free to reopen and ask additional questions related to this topic if issue persists.

**Closed by avitial** 2024-12-26 21:13 UTC
Labels: support_request
